/**
 * Skills Database
 * 
 * Comprehensive list of skills organized by category for autocomplete and suggestions.
 */

export interface SkillCategory {
  id: string
  name: string
  skills: string[]
}

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    id: 'data-ai-analytics',
    name: 'Data, AI & Analytics',
    skills: [
      'Data Modeling',
      'Feature Engineering',
      'Regression',
      'RNN',
      'AWS SageMaker',
      'GPT-4',
      'Pinecone',
      'User Management',
      'ETL Tools',
      'Big Data Tools',
      'Jupyter',
      'System Design for Data',
      'Classification',
      'Advanced SQL',
      'TensorFlow',
      'FAISS',
      'Database Design',
      'Backups',
      'Clustering',
      'SQL Server',
      'OpenAI API',
      'Transformers',
      'Google Vertex AI',
      'PyTorch',
      'Neural Networks',
      'Weights & Biases',
      'MLflow',
      'Data Cleaning',
      'SQL (Basic)',
      'Excel',
      'Google Sheets',
      'Tableau',
      'Deep Learning',
      'Machine Learning',
      'Google BigQuery',
      'scikit-learn',
      'Kubeflow',
      'Prompt Engineering',
      'LangChain',
      'SQL Tuning',
      'Data Visualization',
      'Statistical Analysis',
      'Predictive Modeling',
      'Natural Language Processing',
      'Computer Vision',
      'Reinforcement Learning',
      'Time Series Analysis',
      'A/B Testing',
      'Data Warehousing',
      'Apache Spark',
      'Hadoop',
      'Kafka',
      'Airflow',
      'dbt',
      'Snowflake',
      'Redshift',
      'Power BI',
      'Looker',
      'Qlik',
      'R',
      'Pandas',
      'NumPy',
      'Matplotlib',
      'Seaborn',
      'Plotly',
      'D3.js',
    ],
  },
  {
    id: 'software-development',
    name: 'Software Development',
    skills: [
      'API Testing',
      'HTML/CSS',
      'Python',
      'HTML',
      'Automation Testing',
      'PostgreSQL',
      'React.js',
      'VS Code',
      'MySQL',
      'JavaScript',
      'REST APIs',
      'Git',
      'TypeScript',
      'Node.js',
      'Express.js',
      'Next.js',
      'Vue.js',
      'Angular',
      'Svelte',
      'Django',
      'Flask',
      'FastAPI',
      'Spring Boot',
      'Ruby on Rails',
      'Laravel',
      'ASP.NET',
      'Java',
      'C#',
      'C++',
      'Go',
      'Rust',
      'Swift',
      'Kotlin',
      'PHP',
      'Ruby',
      'Scala',
      'Elixir',
      'Clojure',
      'Haskell',
      'GraphQL',
      'gRPC',
      'WebSocket',
      'Microservices',
      'Docker',
      'Kubernetes',
      'CI/CD',
      'Jenkins',
      'GitHub Actions',
      'GitLab CI',
      'AWS',
      'Azure',
      'GCP',
      'Terraform',
      'Ansible',
      'Chef',
      'Puppet',
      'Linux',
      'Unix',
      'Windows Server',
      'MongoDB',
      'Redis',
      'Elasticsearch',
      'Cassandra',
      'DynamoDB',
      'Firebase',
      'Supabase',
      'Selenium',
      'Cypress',
      'Jest',
      'Mocha',
      'JUnit',
      'Pytest',
      'Unit Testing',
      'Integration Testing',
      'E2E Testing',
      'TDD',
      'BDD',
      'Agile',
      'Scrum',
      'Kanban',
      'DevOps',
      'SRE',
      'System Design',
      'Architecture Patterns',
      'Design Patterns',
      'SOLID Principles',
      'Clean Code',
      'Code Review',
      'Pair Programming',
    ],
  },
  {
    id: 'cloud-infrastructure',
    name: 'Cloud & Infrastructure',
    skills: [
      'AWS',
      'Azure',
      'Google Cloud Platform',
      'AWS EC2',
      'AWS S3',
      'AWS Lambda',
      'AWS RDS',
      'AWS CloudFormation',
      'AWS CloudWatch',
      'AWS IAM',
      'AWS VPC',
      'Azure Functions',
      'Azure DevOps',
      'Azure Active Directory',
      'GCP Compute Engine',
      'GCP Cloud Functions',
      'GCP BigQuery',
      'GCP Cloud Storage',
      'Kubernetes',
      'Docker',
      'Terraform',
      'Ansible',
      'Pulumi',
      'Serverless',
      'Container Orchestration',
      'Load Balancing',
      'Auto Scaling',
      'CDN',
      'Cloud Security',
      'Network Security',
      'Infrastructure as Code',
      'Monitoring',
      'Logging',
      'Alerting',
      'Disaster Recovery',
      'Backup Solutions',
      'High Availability',
      'Performance Optimization',
    ],
  },
  {
    id: 'mobile-development',
    name: 'Mobile Development',
    skills: [
      'iOS Development',
      'Android Development',
      'React Native',
      'Flutter',
      'Swift',
      'SwiftUI',
      'Kotlin',
      'Java (Android)',
      'Objective-C',
      'Xamarin',
      'Ionic',
      'Cordova',
      'PhoneGap',
      'App Store',
      'Google Play',
      'Mobile UI/UX',
      'Mobile Testing',
      'Push Notifications',
      'In-App Purchases',
      'Mobile Analytics',
      'Cross-platform Development',
    ],
  },
  {
    id: 'web-development',
    name: 'Web Development',
    skills: [
      'HTML5',
      'CSS3',
      'JavaScript',
      'TypeScript',
      'React',
      'Vue.js',
      'Angular',
      'Svelte',
      'Next.js',
      'Nuxt.js',
      'Gatsby',
      'Remix',
      'Tailwind CSS',
      'Bootstrap',
      'Material-UI',
      'Chakra UI',
      'Styled Components',
      'SASS',
      'LESS',
      'Webpack',
      'Vite',
      'Parcel',
      'Responsive Design',
      'Progressive Web Apps',
      'Web Accessibility',
      'SEO',
      'Performance Optimization',
      'Web Security',
      'Cross-browser Compatibility',
    ],
  },
  {
    id: 'cybersecurity',
    name: 'Cybersecurity',
    skills: [
      'Penetration Testing',
      'Vulnerability Assessment',
      'Security Auditing',
      'Network Security',
      'Application Security',
      'Cloud Security',
      'Identity & Access Management',
      'Encryption',
      'Cryptography',
      'SIEM',
      'SOC',
      'Incident Response',
      'Threat Intelligence',
      'Security Compliance',
      'OWASP',
      'Firewall Management',
      'Intrusion Detection',
      'Security Policies',
      'Risk Assessment',
      'Security Architecture',
    ],
  },
  {
    id: 'product-management',
    name: 'Product Management',
    skills: [
      'Product Strategy',
      'Roadmap Planning',
      'User Research',
      'Market Research',
      'Competitive Analysis',
      'Product Metrics',
      'A/B Testing',
      'User Stories',
      'Requirements Gathering',
      'Stakeholder Management',
      'Agile',
      'Scrum',
      'Kanban',
      'Product Launch',
      'Go-to-Market Strategy',
      'Product Analytics',
      'User Experience',
      'Wireframing',
      'Prototyping',
      'Figma',
      'Sketch',
      'Adobe XD',
    ],
  },
  {
    id: 'design',
    name: 'Design',
    skills: [
      'UI Design',
      'UX Design',
      'User Research',
      'Wireframing',
      'Prototyping',
      'Figma',
      'Sketch',
      'Adobe XD',
      'Adobe Photoshop',
      'Adobe Illustrator',
      'Adobe InDesign',
      'InVision',
      'Framer',
      'Principle',
      'Design Systems',
      'Component Libraries',
      'Interaction Design',
      'Visual Design',
      'Brand Design',
      'Graphic Design',
      'Illustration',
      'Animation',
      'Motion Design',
    ],
  },
  {
    id: 'devops',
    name: 'DevOps & SRE',
    skills: [
      'CI/CD',
      'Jenkins',
      'GitHub Actions',
      'GitLab CI',
      'CircleCI',
      'Travis CI',
      'Bamboo',
      'Docker',
      'Kubernetes',
      'Helm',
      'Terraform',
      'Ansible',
      'Puppet',
      'Chef',
      'Prometheus',
      'Grafana',
      'ELK Stack',
      'Splunk',
      'New Relic',
      'Datadog',
      'Infrastructure Monitoring',
      'Log Management',
      'Performance Tuning',
      'Capacity Planning',
      'Disaster Recovery',
      'Backup & Restore',
    ],
  },
  {
    id: 'other',
    name: 'Other Skills',
    skills: [
      'Project Management',
      'Agile',
      'Scrum',
      'Kanban',
      'JIRA',
      'Confluence',
      'Slack',
      'Microsoft Office',
      'Google Workspace',
      'Communication',
      'Leadership',
      'Team Management',
      'Problem Solving',
      'Critical Thinking',
      'Time Management',
      'Presentation Skills',
      'Technical Writing',
      'Documentation',
    ],
  },
]

/**
 * Get all skills from all categories
 */
export function getAllSkills(): string[] {
  return SKILL_CATEGORIES.flatMap((category) => category.skills)
}

/**
 * Search skills by query
 */
export function searchSkills(query: string, limit: number = 20): string[] {
  const allSkills = getAllSkills()
  const lowerQuery = query.toLowerCase()
  
  return allSkills
    .filter((skill) => skill.toLowerCase().includes(lowerQuery))
    .slice(0, limit)
}

/**
 * Get skills by category
 */
export function getSkillsByCategory(categoryId: string): string[] {
  const category = SKILL_CATEGORIES.find((cat) => cat.id === categoryId)
  return category?.skills || []
}

